### ISSUE TITLE
Episode #25-26

### ISSUE THREAD

**Issue by php-coder** [php-coder/ps-podcast#22]

**Comment by viartemev** [comment]
https://github.com/radarsh/gradle-test-logger-plugin

**Comment by php-coder** [comment]
https://k3s.io/

**Comment by php-coder** [comment]
[JEP 330](https://openjdk.java.net/jeps/330) is an enhancement in Java 11 that allows you to run a single file of Java source code, without compiling it.
```console
$ java Hello.java
Error: Could not find or load main class Hello.java
```

Wow!

**Comment by viartemev** [comment]
https://github.com/kvz/bash3boilerplate/blob/master/README.md

**Comment by viartemev** [comment]
https://github.com/viartemev/spring-boot-coroutines-demo

**Comment by php-coder** [comment]
https://github.com/corneliusweig/rakkess @viartemev may like this

**Comment by php-coder** [comment]
https://github.com/kubernetes/kubernetes/pull/67573 stern в опасносте? :)

**Comment by php-coder** [comment]
Did you know about exception optimization in JVM and `-XX:-OmitStackTraceInFastThrow` option?
See https://stackoverflow.com/questions/2411487/nullpointerexception-in-java-with-no-stacktrace

**Comment by viartemev** [comment]
http://august.nagro.us/small-java.html

**Comment by viartemev** [comment]
https://quarkus.io/

**Comment by viartemev** [comment]
https://github.com/reactor/BlockHound

**Comment by asm0dey** [comment]
https://github.com/kvz/bash3boilerplate/blob/master/README.md

**Comment by viartemev** [comment]
https://github.com/netdata/netdata

**Comment by asm0dey** [comment]
https://awesomelists.top/

**Comment by viartemev** [comment]
https://github.com/trello/mr-clean

**Comment by asm0dey** [comment]
https://facebook.github.io/watchman/

**Comment by viartemev** [comment]
https://developers.google.com/web/tools/lighthouse/

**Comment by php-coder** [comment]
https://github.com/moby/moby/issues/38879 and https://github.com/Tecnativa/docker-socket-proxy

**Comment by php-coder** [comment]
https://github.com/hjacobs/kube-ops-view

**Comment by php-coder** [comment]
https://github.com/hharnisc/kubescope-cli

**Comment by php-coder** [comment]
https://pgtune.leopard.in.ua и http://pgconfigurator.cybertec.at

**Comment by asm0dey** [comment]
https://github.com/jacobtomlinson/krontab

**Comment by viartemev** [comment]
https://github.com/danistefanovic/build-your-own-x

**Comment by viartemev** [comment]
https://openjdk.java.net/jeps/8220715

**Comment by php-coder** [comment]
Published:
* https://it.asm0dey.ru/podcast/паша-слава-эп-25-тимлидское/
* https://it.asm0dey.ru/podcast/%d0%bf%d0%b0%d1%88%d0%b0-%d1%81%d0%bb%d0%b0%d0%b2%d0%b0-%d1%8d%d0%bf-26-%d0%bf%d0%be%d0%bb%d0%b5%d0%b7%d0%bd%d1%8f%d1%88%d0%ba%d0%b8/
