### ISSUE TITLE
Episode #51

### ISSUE THREAD

**Issue by viartemev** [php-coder/ps-podcast#51]

**Comment by viartemev** [comment]
https://github.com/alimate/errors-spring-boot-starter

**Comment by viartemev** [comment]
https://github.com/Netflix-Skunkworks/jvmquake

**Comment by php-coder** [comment]
https://pythonspeed.com/articles/dont-need-kubernetes/ #kubernetes

**Comment by viartemev** [comment]
https://github.com/tonsky/AnyBar

**Comment by asm0dey** [comment]
https://cloud.google.com/blog/products/application-development/use-grpc-with-kotlin

**Comment by viartemev** [comment]
https://github.com/spring-projects/spring-boot/issues/4657

**Comment by asm0dey** [comment]
by https://t.me/asm0dey:
https://github.com/mingrammer/diagrams/

**Comment by asm0dey** [comment]
https://snakemake.readthedocs.io/en/stable/

**Comment by asm0dey** [comment]
https://github.com/AdoptOpenJDK/jitwatch/wiki

**Comment by php-coder** [comment]
Published: https://it.asm0dey.ru/podcast/generate-this/
