### ISSUE TITLE
Issue #13

### ISSUE THREAD

**Issue by asm0dey** [php-coder/ps-podcast#9]
https://springframework.guru/what-is-new-with-spring-framework-5/
Котлин-конфигурация вместо `@Bean`, `@Configuration`, XML и groovy!

**Comment by php-coder** [comment]
Common Pitfalls When Writing BDD Specifications
https://medium.com/@njenan/common-pitfalls-when-writing-bdd-specifications-f45f72179570

**Comment by asm0dey** [comment]
https://www.beyondjava.net/blog/vertxui-java-front-end-language/
writing html in java

**Comment by php-coder** [comment]
Kubernetes v1.7 security in practice
https://acotten.com/post/kube17-security

**Comment by php-coder** [comment]
Introduction to the Functional Web Framework in Spring 5
http://www.baeldung.com/spring-5-functional-web

**Comment by asm0dey** [comment]
https://it.asm0dey.ru/podcast/%D1%81%D0%BB%D0%B0%D0%B2%D0%B0-%D0%BF%D0%B0%D1%88%D0%B0-%D1%8D%D0%BF%D0%B8%D0%B7%D0%BE%D0%B4-13-%D0%BE-%D0%B1%D0%BE%D0%BB%D1%8F%D1%85/
